### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by atenreiro** [Snbig/InstaTrack#15]
Hello,

The script stopped working possible due to Instagram changes in their page. 

![image](https://user-images.githubusercontent.com/10222828/86520812-d7765280-be48-11ea-9343-8acec0b059a4.png)

**Comment by Snbig** [comment]
Instagram has changed the query_hash page from "ProfilePageContainer.js" to "ConsumerLibCommons.js".
I fixed the issue.
Thank you for your advice.

**Comment by atenreiro** [comment]
Hello Snbig,

Still having issues:

![image](https://user-images.githubusercontent.com/10222828/86530544-d2052080-beb9-11ea-8d19-6e3d3c113478.png)

**Comment by Snbig** [comment]
> Hello Snbig,
> 
> Still having issues:
> 
> ![image](https://user-images.githubusercontent.com/10222828/86530544-d2052080-beb9-11ea-8d19-6e3d3c113478.png)

I executed the code without any problem.
Your problem is because you are jsondecode "None" object. if "r" value is "None" too, it might you got rate limited or your ip is blacklisted.

**Comment by atenreiro** [comment]
Hello,

I've tried with two machines running different Public IP addresses on AWS. None of them works. Removed old InstaTrack and cloned the latest available.

Happy to provide you with any logs that might help the troubleshoot.

**Comment by Snbig** [comment]
> Hello,
> 
> I've tried with two machines running different Public IP addresses on AWS. None of them works. Removed old InstaTrack and cloned the latest available.
> 
> Happy to provide you with any logs that might help the troubleshoot.

Yes, sure.
As far as i know Instagram has different behavior in various countries.
For troubleshooting the main code:
1. Is "r" value "None"?
2. If it is not, what's the stuff?

**Comment by atenreiro** [comment]
The output that I'm getting using the following command arg: **-u instagram**

**r variable output**:
https://pastebin.com/GCfNbBRS

It breaks when doing the comparison:
`line 45: if json.loads(r).get("message") == 'rate limited':`
`

**Comment by darylkell** [comment]
When using -i <id>, json.loads(r) is now returning `{'data': {'viewer': None, 'user': None}, 'status': 'ok'}`.
-u still working fine.

**Comment by Snbig** [comment]
Instagram is limiting the use of its API for not logged in users.
I could fix "useridToUsername".
I'm trying to fix "usernameToUserId" too.

**Comment by atenreiro** [comment]
> Instagram is limiting the use of its API for not logged in users.
> I could fix "useridToUsername".
> I'm trying to fix "usernameToUserId" too.

Let me know if you need a Tester

**Comment by mos3b-faqeeh** [comment]
useridToUsername still getting error (page not found).
